#!/bin/sh



lightsensor="/sys/bus/platform/drivers/applesmc/applesmc.768/light"
kblight="/sys/bus/platform/drivers/applesmc/applesmc.768/leds/smc::kbd_backlight/brightness"
screenlight="/dev/null"


### Defines for sensor behaviour
# Maximum values
light_max=255
kb_max=255
screen_max=1808
# Noticable differences
kb_diff=10
screen_diff=50

__calclight()
{

	light=$1; shift
	maxval=$1; shift
	if [ $light_max -ne $maxval ]; then
		light=$(($light * $maxval / $light_max))
	fi
	retval=$(($maxval - $light))
	echo $retval
}


while true; do
	light=$(sed 's/^(\(.*\),.*)/\1/' "$lightsensor")
	kblightval=$(__calclight $light $kb_max)
	printf "kblightval: %s\\n" $kblightval
	screenlightval=$(__calclight $light $screen_max)
	printf "screenlightval: %s\\n" $screenlightval
	sleep 1
done
